pkg/backup/client.go
pkg/backup/safe_point.go

Fail fast if the backup ts exceed GC safe point ts.

backup: check GC fail fast

---

pkg/backup/client.go

TiKV master uses a new backup scanner, full backup requires zero start version.

backup: set zero start version to be compatible with latest tikv

---

pkg/conn/conn.go
pkg/conn/conn_test.go

Encode keys into memcomparable-format before calling `stats/region`.
Fix #125

conn: fix inaccurate region count

---

pkg/restore/db.go
pkg/restore/db_test.go
pkg/restore/util.go
tests/br_insert_after_restore/run.sh

Signed-off-by: 5kbpers <tangminghua@pingcap.com>
Previously we rely on CREATE TABLE SQL to recover AutoIncID, but the API TiDB supplied does not set AutoIncID in CREATE TABLE when a table does not have a primary key.
Now we change to execute an `Alter AutoIncrementID` SQL after creating a table.

restore: fix alter auto increment id for no-primary-key table

---

cmd/restore.go

Restoring a database or table giving a table name that does not exist in the given backup causes SIGSEGV:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56192dd]
goroutine 1 [running]:
github.com/pingcap/br/cmd.runRestore(0xc000328c00, 0x5b77dc9, 0x10, 0x7ffeefbff98d, 0x3, 0x0, 0x0, 0x0, 0x0)
/Users/kolbe/Devel/git/pingcap/br/cmd/restore.go:114 +0x122d
github.com/pingcap/br/cmd.newDbRestoreCommand.func1(0xc00037b180, 0xc000626240, 0x0, 0x4, 0x0, 0x0)
/Users/kolbe/Devel/git/pingcap/br/cmd/restore.go:234 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00037b180, 0xc00004e0a0, 0x4, 0x4, 0xc00037b180, 0xc00004e0a0)
/Users/kolbe/Devel/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460 …
```

Fixed handling for a dbName that do not exist in the backup being restored

---

tests/br_debug_meta/run.sh

Fix debug_meta ci failed
check the rowcount before and after backup 
Tests 

validate: fix debug meta test ci

---

.codecov.yml
pkg/restore/backoff.go
pkg/restore/import.go
tests/_utils/run_services
tests/br_table_partition/run.sh

Speed up retry on not leader, also stable CI by waiting for TiKV initialization.
Add a fast path for getting leader info from response.
Tests 
Side effects
Close #177

restore: speed up retry on not leader

---

pkg/conn/conn.go
pkg/glue/glue.go
pkg/gluetidb/glue.go

When integrating BR into TiDB, the BR glue will reuse the storage & domain & session from the caller.
However, currently the `conn.Mgr` unconditionally closes the storage & domain, causing double-close panic at the end of BACKUP/RESTORE.
Added a method to `glue.Glue` indicating whether the storage & domain is "owned" or "borrowed". Change `(*conn.Mgr).Close()` to avoid closing the storage & domain when they are "borrowed".
Tests 
* pingcap/tidb#15274 works after including this change.
Code changes
* `glue.Glue` has a new method.
Side effects

conn: support not shutting down the storage when closing the connection

---

cmd/backup.go
cmd/restore.go
pkg/conn/conn.go
pkg/glue/glue.go
pkg/gluetidb/glue.go
pkg/utils/progress.go

TiDB Bootstrap API may include some breaking changes that breaks BR too. 
Use GetDomain to avoid some TiDB breaking changes.
Tests 

conn: use GetDomain to avoid some TiDB breaking changes

---

pkg/backup/client.go
pkg/backup/client_test.go
pkg/task/backup.go
pkg/task/backup_test.go
pkg/task/common.go

finish issue #170 
* use same concept as [tidb snapshot](https://pingcap.com/docs/stable/how-to/get-started/read-historical-data/) to set certain backupts to br
* update storage help message: default `local:` -> `s3`
Tests 
- Unit test

support backupts

---

pkg/backup/client.go
pkg/restore/client.go
pkg/restore/import.go
pkg/summary/collector.go
pkg/summary/summary.go
pkg/task/restore.go

Fix restore summary log, after restore unit has been change from `table` to `file`.
changed restore summary unit to file
Tests 
- Manual test 

Fix summary log

---

pkg/restore/db.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/task/restore.go
pkg/task/restore_raw.go

always put summary output at last 
move defer summary in the front of `runBackup`/`runRestore`
Tests 
- Manual test

summary: put summary log at last

---

pkg/backup/client.go
pkg/backup/push.go
pkg/backup/schema.go
pkg/backup/schema_test.go
pkg/glue/glue.go
pkg/gluetidb/glue.go
pkg/gluetikv/glue.go
pkg/restore/client.go
pkg/restore/util.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/task/restore.go
pkg/task/restore_raw.go

Integrating BR into TiDB requires the caller to know the current progress in order to report it in the SQL result. The current implementation only supports either printing to log or stdout, which is insufficient for the purpose.
Move the `utils.StartProgress` function into the `Glue`, so that the TiDB integration can provide its own progress reporting mechanism.
Tests 
- Unit test
Code changes
* New method in `glue.Glue`.
Side effects

*: abstract the progress channel (updateCh) into the glue package

---

tests/run.sh

Latest TiKV core dumps (tikv/tikv#7209) when TLS is enabled and blocks BR pull requests.
To unblock BR pull requests we have to disable TLS test temporarily.
Tests 

tests: disable TLS test

---

cmd/backup.go
cmd/restore.go
go.mod
go.sum
main.go

1. SilenceUsage=false only when parse cmd flags error happen
2. update tidb version to fix https://github.com/pingcap/tidb/issues/15479
as above said
Tests 
- Manual test
Code changes
- Need to cherry-pick to the release-3.1 release-4.0

enhance usability of br

---

pkg/task/restore.go
pkg/task/restore_raw.go

Previously when restore failed, the checksum was still executed. This caused the final reported error to be always "checksum failed" which is misleading.
After all the "post-work" jobs are complete, if restore has an error immediately return.
Tests 
Code changes
Side effects

task: do not run checksum if restore failed

---

pkg/backup/client.go
pkg/backup/schema_test.go
pkg/restore/db.go
pkg/task/backup.go
pkg/task/restore.go
tests/br_incremental_only_ddl/run.sh
tests/br_incremental_same_table/run.sh

1. Fix filter ddl bug. in some case that ddls has same tableName but different DB name
2. incremental restore should execute DDL before create Database.
3. `nothing to do` shouldn't return error, because even if there is no sst files, we still need to execute ddl jobs as soon as possible in restore.
Tests 
- Manual test

fix incremental bug in llroad test

---

pkg/restore/client.go
pkg/task/restore.go
tests/br_db_skip/run.sh

skip create sqls in restore, this may use when user has already use br create tables and databases but broken during restore, because user may have lots of tables, skip retry creates sql will save time.
1.add `skipCreateSQL` and check whether we can skip before `createDatabases` and `createTables`
Tests 

add skip create sqls

---

tests/run.sh

Revert "tests: disable TLS test"

---

tests/README.md

The README of test omitted one necessary dependence.
I added the omitted dependency, `minio`.
Tests 
- No code

README of test omitted one third-party dependence.

---

pkg/restore/client.go
pkg/restore/client_test.go
pkg/restore/import.go
pkg/restore/split.go
pkg/restore/split_test.go
pkg/restore/util.go
pkg/task/restore.go

currently we have issue when deal with tiflash stores:
to reproduce it, we can assume
1. we have two tables, t1 and t2
* t1 has 100000 record
* t2 has 10 record
2. alter table `t1` set tiflash replica 1;
3. br backup table --db xxx --table `t2` -s ... --pd ...
4. br restore table --db xxx --table `t2` -s ... --pd ...
then we may get this log until waiting out of time
```
[2020/03/31 17:57:12.714 +08:00] [INFO] [split.go:150] ["start to wait for removing rejected stores"] [rejectStores="{\"92\":true}"]
```
this because `t2` and `t1` may be in the same region. and the condition of waiting rejected store is whether [region has tiflash store peers](https://github.com/pingcap/br/blob/6268cde45e6a05b5e46d1208b31ea18a1770b8ba/pkg/restore/split.go#L292)
move `wait reject store` logic after import …

move waiting reject stores in import file

---

pkg/gluetidb/glue.go
pkg/task/restore.go

Fix #217 
add flag to set max-index-length when restoring data
Tests 
- Manual test (according to #217)

Max index length

---

pkg/restore/db.go
pkg/task/restore.go
tests/br_incompatible_tidb_config/run.sh

Fix https://github.com/pingcap/br/pull/230#issuecomment-610798266
1. use `ddljob.TableInfo` and `ddljob.DBInfo` to create tables and schema in incremental restore.
2. set `config.AlterPrimaryKey` to true so we can execute drop/add pk DDL in incremental restore.
Tests 
Code changes
Side effects

Use table info

---

cmd/cmd.go

`:` is not a valid filename character for NTFS. The default log file path contains a `:` and thus invalid.
Replace the `:` in the filename by `.`.
Tests 
* run `bin/br --help` and check the output.
Code changes
Side effects

cmd: don't use ':' in the default log file name

---

pkg/storage/parse.go
pkg/storage/parse_test.go
tests/br_s3/run.sh

pingcap/tidb#15274 requires a function to parse the URL parameters into actual options. For compatibility, we'd like to introduce this feature into BR as well, so you could write e.g.
```sh
./br backup -s 's3://bucket/prefix?region=us-west-2'
```
We introduced a new function `storage.ExtractQueryParameters(url, &options)` to be shared by both TiDB and BR itself for moving query parameters from the URL into the S3/GCS options. We used reflection to avoid repeating the keys. Parameter keys follow the JSON keys in the struct tags.
BTW, added `gs://` as alias of `gcs://`.
Tests 
- Unit test
Code changes
Side effects
- Need to be included in the release note
* Mention that there are now two ways to provide the parameters: …

storage: support placing the S3/GCS options into the storage URL

---

pkg/backup/client.go
pkg/backup/safe_point.go
pkg/backup/safe_point_test.go
pkg/task/backup.go
tests/br_z_gc_safepoint/gc.go
tests/br_z_gc_safepoint/run.sh

This PR can register backupTS as safePoint to PD, so the SafePoint won't move forward during backup. Avoid manually set GC safePoint.
Use `pdClient.UpdateServiceSafePoint` interface to lock down safePoint with TTL(60 secs)
Tests 
- No code
need cherry-pick to release-4.0
- Need to be included in the release note

Backup: register backupTS as safepoint to PD 

---

pkg/backup/client.go
pkg/backup/safe_point.go
pkg/backup/safe_point_test.go
pkg/task/backup.go
tests/br_z_gc_safepoint/gc.go
tests/br_z_gc_safepoint/run.sh

cherry-pick #257 to release-4.0
This PR can register backupTS as safePoint to PD, so the SafePoint won't move forward during backup. Avoid manually set GC safePoint.
Use `pdClient.UpdateServiceSafePoint` interface to lock down safePoint with TTL(60 secs)
Tests 
- No code
need cherry-pick to release-4.0
- Need to be included in the release note

cherry-pick to release 4.0

---

.gitignore
go.mod
go.sum
pkg/storage/s3.go

Pass sse_kms_key_id when backup to S3. This is to support using user owned KMS key for server-side encryption.
Pass sse_kms_key_id when backup to S3 to both tikv and when storing backupmeta in S3.
Tests 
Manual test with BR. Try:
* specify kms key id on backup. restore success.
* disable the kms key and try restore again. restore failed.
depends on kvproto change: https://github.com/pingcap/kvproto/pull/607 and tikv change: https://github.com/tikv/tikv/pull/7627
Signed-off-by: Yi Wu <yiwu@pingcap.com>
Co-authored-by: kennytm <kennytm@gmail.com>

pass sse_kms_key_id to S3 (#243)

---

.github/pull_request_template.md

The new "release note checker" bot demands a "Release note" section 🤖.
Replaced the original "Need to be included in the release note" item by a "Release note" section.
Tests 
- No code
Code changes
Side effects
* No release note

.github: change the PR template to include the "Release note" section

---

Makefile
go.mod
go.sum
pkg/restore/split_client.go
tests/br_split_region_fail/run.sh
tests/br_split_region_fail/workload
tools/Makefile
tools/go.mod
tools/go.sum
tools/go_mod_guard.go

cherry-pick #247 to relase 4.0 manually.

cherry-pick #247 to relase 4.0

---

tests/_utils/run_services

try to fix integration_test failed with `Failed to initialize TiKV cluster`
wait tikv 100 seconds to start
Tests 

tests: wait tikv 100 seconds to init

---

cmd/backup.go
cmd/restore.go
cmd/validate.go
pkg/backup/client.go
pkg/task/common.go
pkg/task/common_test.go
pkg/utils/version.go
tests/br_s3/run.sh

fix [bug hunting #71](https://github.com/tidb-challenge-program/bug-hunting-issue/issues/71)
I change the line that logging the secret information:
https://github.com/pingcap/br/blob/00fe08c83ed64f8e0461577f1310dc9eed8f0407/pkg/backup/client.go#L763
Tests 
- Unit test
- No code
Code changes
- Has exported function/method change(move `LogArguments` from `utils` to `task`).

Don't log secret of s3.

---

tests/br_incompatible_tidb_config/run.sh

Because of [tidb#17119](https://github.com/pingcap/tidb/pull/17119), current version of `br_incompatible_tidb_config` will fail: 
```
[2020-05-18T02:14:18.885Z] ERROR 8216 (HY000) at line 1: Invalid auto random: auto_random option must be defined on `bigint` column, but not on `int` column
```
Because we use a int column with auto_random...
https://github.com/pingcap/br/blob/c2f193cd09da31f811eae192bf375eda42016ecd/tests/br_incompatible_tidb_config/run.sh#L92
I changed type of columns with auto_random in the test case to bigint.
Tests 
- No code

change auto_random columns to bigint.

---

go.mod
go.sum
pkg/backup/client.go
pkg/restore/split_client.go
tests/br_key_locked/codec.go

Tests 
- Unit test
- No code
Code changes
Side effects
-

br: fit the recent pd client

---

pkg/backup/client.go
pkg/restore/db.go
tests/br_views_and_sequences/run.sh
tests/download_tools.sh

cherry-pick #242 to release-4.0
Fix #145, and also support backup/restore sequences.
Thanks to #216, views and sequences can be naturally restored.
The only problems left are
1. Views don't have auto IDs.  This PR skips the auto-ID rebase when the table is a view.
2. Value of sequence needs to be backed up. This PR stores the current sequence value into the `AutoIncID` field, and performs `setval()` on restore.
Tests 
Code changes
Side effects
- Need to be included in the release note
* BR now supports views and sequences.

Support backup & restore views and sequences (#242)

---

pkg/restore/import.go
pkg/restore/util.go
pkg/restore/util_test.go
tests/br_range/run.sh

Try fix row data lost.
row id bigger than 9151314442816847872 after encoded may exceed than default max range end [`0xff`]( https://github.com/pingcap/br/blob/943e502cc14da6bff81d15b78d2468500526a44b/pkg/restore/util.go#L106), change it `10*[0xff]`
Tests 
- manual test
- Fix the row data lost when row_id bigger than 9151314442816847872

Fix row data lost

---

cmd/backup.go
cmd/restore.go

fix #309 
I add log at `runXxxxCommand` if receive an error from `RunXxxx`. 
Tests 
Old version, run BR with empty storage, no error message log to log file: 
New version, an error record presents in the log file:
- Add log on failure.

tasks: print error to log after fail.

---

pkg/restore/import.go
pkg/restore/util.go
pkg/restore/util_test.go
tests/br_range/run.sh
tools/go.sum

cherry-pick #315 to release-3.1
Try fix row data lost.
row id bigger than 9151314442816847872 after encoded may exceed than default max range end [`0xff`]( https://github.com/pingcap/br/blob/943e502cc14da6bff81d15b78d2468500526a44b/pkg/restore/util.go#L106), change it `10*[0xff]`
Tests 
- manual test
- Fix the row data lost when row_id bigger than 9151314442816847872

Cherry-pick:  row data lost (#315)

---

pkg/restore/backoff.go
pkg/restore/backoff_test.go
pkg/restore/import.go
pkg/utils/retry.go

Cherry-pick #298 to release-3.1
Tests 
- Unit test
Code changes
Side effects
- Improved robustness of restore, reducing chance of failure due to transient network error with cloud storage.

[3.1] restore: Make all download error as retryable (#298)

---

Makefile
pkg/conn/conn.go
pkg/restore/import.go
pkg/task/common.go
pkg/task/restore.go
pkg/utils/math.go
pkg/utils/math_test.go
tests/README.md
tests/_utils/make_tiflash_config
tests/_utils/run_services
tests/br_rawkv/run.sh
tests/br_tiflash/run.sh
tests/config/pd.toml
tests/download_tools.sh

cherry-pick #327 to 4.0(manually)
--- 
Currently, we have no test cases with TiFlash, this PR add TiFlash to test cluster.
And, at post, we should remove all TiFlash replicas so that we backup or restore successfully without failed by 'RPC unimplemented', this PR also add a flag to disable this function, for farther test usage.  
I replace `store.GetAddr()` to `store.GetPeerAddr() || store.GetAddr()`, because TiFlash use a 'proxy' to act like a TiKV, its 'address' is more like a 'service' address but a 'peer' address. Hence, we should try get `PeerAddr` firstly, and normal TiKV has no `PeerAddr`, so we use `Addr` as a fallback.
And I added a one-node TiFlash to the integration test cluster.
Tests 
+ Manual test (add detailed scripts or steps below)
- Start a cluster …

cherry-pick #327 to 4.0

---

Makefile
pkg/conn/conn.go
pkg/restore/import.go
pkg/task/common.go
pkg/task/restore.go
pkg/utils/math.go
pkg/utils/math_test.go
tests/README.md
tests/_utils/make_tiflash_config
tests/_utils/run_services
tests/br_rawkv/run.sh
tests/br_tiflash/run.sh
tests/config/pd.toml
tests/download_tools.sh

cherry-pick #327 to 3.1 (manually)
--- 
Currently, we have no test cases with TiFlash, this PR add TiFlash to test cluster.
And, at post, we should remove all TiFlash replicas so that we backup or restore successfully without failed by 'RPC unimplemented', this PR also add a flag to disable this function, for farther test usage.  
I replace `store.GetAddr()` to `store.GetPeerAddr() || store.GetAddr()`, because TiFlash use a 'proxy' to act like a TiKV, its 'address' is more like a 'service' address but a 'peer' address. Hence, we should try get `PeerAddr` firstly, and normal TiKV has no `PeerAddr`, so we use `Addr` as a fallback.
And I added a one-node TiFlash to the integration test cluster.
Tests 
+ Manual test (add detailed scripts or steps below)
- Start a cluster …

cherry-pick #327 to 3.1

---

pkg/utils/progress.go
pkg/utils/progress_test.go

Fix item 5 of #259.
1. Do not start the progress bar before it was fully configured (so that the refresh rate can really be respected).
2. Further increased the refresh rate when BR_LOG_TO_TERM=1 from 10s to 2m.
3. Included more progress information into the log when BR_LOG_TO_TERM=1:
```
[2020/06/04 20:01:14.965 +00:00] [INFO] [progress.go:113] [progress] [step="Full restore"] [progress=29.18%] [count="700 / 2399"] [speed="11 p/s"] [elapsed=48s] [remaining=2m34s]
```
Tests 
- Unit test
* Execute BR manually with BR_LOG_TO_TERM=1 and inspect the output.
Code changes
Side effects
- Reduced the excessive refresh rate of progress logs when logging to terminal (e.g. when using K8s).

utils: fix excessive refresh frequency when BR_LOG_TO_TERM=1

---

pkg/restore/backoff.go
pkg/restore/backoff_test.go
pkg/restore/import.go

Fix #333.
The gRPC error from `Ingest` is returned raw. The raw gRPC error is not recognized by `utils.WithRetry`, so any gRPC error from ingest will fail immediately.
This PR:
1. Gets rid of the `ErrGRPC` error, and instead just use `status.Codes` to check if the error is really a gRPC error. Thus gRPC errors from IngestSST would also be covered.
2. Restricts the retryable gRPC errors to only "Aborted" and "Unavailable", as described in https://pkg.go.dev/google.golang.org/grpc/codes?tab=doc#Code. Thus legit "Unknown" error wouldn't be retried.
(Potential problem: currently the entire import process would restart from scratch, rather than just the IngestSST RPC.)
Tests 
- Unit test
* (DBaaS is going to re-test using this PR)
Code …

restore: replace ErrGRPC by recognizing raw gRPC errors

---

pkg/task/restore.go

See pingcap/tidb#17882.
Related TiDB PR: pingcap/tidb#16596.
Tests 
- Unit test
Code changes
Side effects
- The column attribute `auto_random` gets stable and it can be used without the config option `allow-auto-random`.

restore: remove auto_random option

---

cmd/backup.go
cmd/restore.go
go.mod
go.sum
pkg/backup/client.go
pkg/backup/schema_test.go
pkg/task/backup.go
pkg/task/common.go
pkg/task/restore.go
tests/br_table_filter/run.sh

Fix #173, fix #178.
```sh
./br backup full -f 'db1.*' -f 'db2.tbl1' -f '!*.secrets' ...
```
Use the new table-filter package in pingcap/tidb-tools#341.
Tests 
Code changes
* `task.Config` has a new field `TableFilter`. The original two fields `CaseSensitive` and `Filter` are deprecated and should be removed after TiDB upgrades its BR dependency.
Side effects
* should be included for 4.0.1.
* should document the new table filter format (a common page for all tools).
- Supports advanced table filtering.

task: expose table filter for `backup full` and `restore full`

---

.gitignore
pkg/restore/batcher.go
pkg/restore/batcher_test.go
pkg/restore/client.go
pkg/restore/pipeline_items.go
pkg/restore/range.go
pkg/restore/util.go
pkg/restore/util_test.go
pkg/task/restore.go
tests/br_db_online_newkv/run.sh
tests/br_small_batch_size/run.sh
tests/br_small_batch_size/workload

Cherry-pick #266 manually to release-4.0.
--- 
Currently, the full restore workflow is:
1. Firstly, create all tables, collect their new table IDs, and make rewrite rules by it.
2. Then, use those metadata to split regions, and ingest SST files.
That would be good if there are few tables, but when the number of table grows, the time we waste on create table will also be greatly incremented. F1 DDL is slow, even TiDB make great effort  on optimize it, create a table will spend about 2 secs, and cannot be paralleled. 
I pipelined the workflow, that is, we won't wait until all tables created. (e.g. we can do restore and create tables at the same time).
Tests 
- Unit test
We tested this on a 3-TiKV cluster, in the 500+ …

Cherry-pick Pipelined restore (#266) to 4.0

---

cmd/validate.go
pkg/backup/client.go
pkg/restore/import.go
pkg/restore/range.go
pkg/restore/split.go
pkg/restore/util.go
pkg/rtree/rtree.go
pkg/utils/logging.go

Done the backlog (6) in #259 
Replace all of these:
`zap.(Binary|ByteString)\("(.*)", (.*)\)` => `zap.Stringer("$1", utils.WrapKey($2))`
`zap.ByteStrings\("(.*)", (.*)\)` => `zap.Array("$1", utils.WrapKeys($2))`
`zap.Any("sstMeta", (.*))` => `utils.ZapSSTMeta($1)`
`zap.Any("region", (.*))` => `utils.ZapRegion($1)`
`zap.Any("rewriteRule", (.*))` => `utils.ZapRewriteRule($1)`
`zap.Any("file", (.*))` => `utils.ZapFile($1)`
Tests 
- See log files provided below.
- Unify the form of keys in logger to hex string. 
Here are some simple logs after changed, logs with '_r' suffix are restore logs:
[log_first.log](https://github.com/pingcap/br/files/4784565/log_first.log)
[log_first_r.log](https://github.com/pingcap/br/files/4784566/log_first_r.log) …

Print keys on log as hex string

---

cmd/validate.go
pkg/backup/client.go
pkg/restore/import.go
pkg/restore/range.go
pkg/restore/split.go
pkg/restore/util.go
pkg/rtree/rtree.go
pkg/utils/logging.go

cherry-pick #359 to 4.0
--- 
Done the backlog (6) in #259 
Replace all of these:
`zap.(Binary|ByteString)\("(.*)", (.*)\)` => `zap.Stringer("$1", utils.WrapKey($2))`
`zap.ByteStrings\("(.*)", (.*)\)` => `zap.Array("$1", utils.WrapKeys($2))`
`zap.Any("sstMeta", (.*))` => `utils.ZapSSTMeta($1)`
`zap.Any("region", (.*))` => `utils.ZapRegion($1)`
`zap.Any("rewriteRule", (.*))` => `utils.ZapRewriteRule($1)`
`zap.Any("file", (.*))` => `utils.ZapFile($1)`
Tests 
- See log files provided below.
- Unify the form of keys in logger to hex string. 
Here are some simple logs after changed, logs with '_r' suffix are restore logs:
[log_first.log](https://github.com/pingcap/br/files/4784565/log_first.log) …

cherry-pick #359 to 4.0

---

.gitignore
pkg/restore/batcher.go
pkg/restore/batcher_test.go
pkg/restore/client.go
pkg/restore/pipeline_items.go
pkg/restore/range.go
pkg/restore/util.go
pkg/restore/util_test.go
pkg/task/restore.go
tests/br_db_online_newkv/run.sh
tests/br_small_batch_size/run.sh
tests/br_small_batch_size/workload

Cherry-pick #266 to release-3.1
---
Currently, the full restore workflow is:
1. Firstly, create all tables, collect their new table IDs, and make rewrite rules by it.
2. Then, use those metadata to split regions, and ingest SST files.
That would be good if there are few tables, but when the number of table grows, the time we waste on create table will also be greatly incremented. F1 DDL is slow, even TiDB make great effort  on optimize it, create a table will spend about 2 secs, and cannot be paralleled. 
I pipelined the workflow, that is, we won't wait until all tables created. (e.g. we can do restore and create tables at the same time).
Tests 
- Unit test
We tested this on a 3-TiKV cluster, in the 500+ table, per …

Cherry-pick #266 to release-3.1

---

pkg/backup/client.go
pkg/task/backup.go
pkg/utils/schema.go
tests/br_other/run.sh

Fix https://github.com/pingcap/br/issues/328
Add a lock file at beginning, to make sure other backup task won't be able to start backup.
Add a lock file when storage created.
Tests 
- Fix the issue that fast fail when multiple backup task start backup on same path.

br: add lock file

---

main.go

Currently when we received an OS signal (e.g. SIGHUP), it is only printed to stdout, which is usually not saved.
Write the message to log in additional to stdout.
Tests 
* run BR and press Ctrl+C, check that a warning is present in the log.
Code changes
Side effects

main: log the received OS signal

---

pkg/backup/client.go
pkg/gluetikv/glue.go
pkg/summary/collector.go
pkg/summary/summary.go
pkg/task/backup.go
pkg/task/restore.go

1. Resolve #365 
1. use `dom.InfoSchema()` to check whether db and tables already exists in target cluster. to skip execute unnecessary DDL.
2. record `backupts` in summary log to enhance usability.
Tests 
From below log, we can tell the increment restore will skip 
1. exists databases and tables created by full restore.
2. record DDL job during increment backup.
```
[client.go:538] ["execute ddl query"] [db=test] [query="create table t2(id int)"] [historySchemaVersion=102]
[restore.go:633] ["detective exists schemas to skip"] [db="[test]"] [table="[t,t2,warehouse,district,new_order,item,history,orders,customer,stock,order_line]"]
```
Code changes …

ignore exists table when restore tables

---

pkg/backup/client.go
pkg/summary/collector.go
pkg/summary/summary.go
pkg/task/backup.go

cherry-pick #384 to release-3.1
---
1. Resolve #365 
1. use `dom.InfoSchema()` to check whether db and tables already exists in target cluster. to skip execute unnecessary DDL.
2. record `backupts` in summary log to enhance usability.
Tests 
From below log, we can tell the increment restore will skip 
1. exists databases and tables created by full restore.
2. record DDL job during increment backup.
```
[client.go:538] ["execute ddl query"] [db=test] [query="create table t2(id int)"] [historySchemaVersion=102]
[restore.go:633] ["detective exists schemas to skip"] [db="[test]"] [table="[t,t2,warehouse,district,new_order,item,history,orders,customer,stock,order_line]"]
```
Code changes
- Need …

ignore exists table when restore tables (#384)

---

go.mod
pkg/backup/client.go
pkg/backup/schema.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/utils/worker.go

Step 2 of #394.
Previously `BackupRanges` execute each `BackupRange` sequentially. When the number of ranges is lot and each range cannot spawn too many backup jobs, this will create a bottleneck.
This PR changes `BackupRanges` to execute each `BackupRange` in parallel. 
As pointed out in #394, the meaning of "concurrency" is changed to mean the number of `BackupRange`s being executed in parallel, rather than the thread pool size in TiKV (this also prevents killing the TiKV servers by supplying an extremely large concurrency).
`BackupRawRanges` is currently not changed since it only has a single range.
**Update 2020/07/04**: It was found that running `BackupRanges` in parallel will cause a race condition since all writes to the same internal field `bc.backupMeta.Files`, and causes some …

*: run BackupRanges in parallel, change meaning of backup concurrency

---

pkg/backup/client.go
pkg/task/backup.go
pkg/utils/schema.go
tests/_utils/run_services
tests/br_other/run.sh
tests/br_tiflash/run.sh

NOTE: because #367 requires #358, so I cherry-picked them together.
#358  
---
Fix https://github.com/pingcap/br/issues/328
Add a lock file at beginning, to make sure other backup task won't be able to start backup.
Add a lock file when storage created.
Tests 
- Fix the issue that fast fail when multiple backup task start backup on same path.
---
#367 
---
BR unit tests sometimes will fail because cannot start cluster(sometimes TiKV, sometimes TiFlash).
- Change a new way to check whether TiFlash is started.
- Add a three times retry if fail to start test cluster.
- Change TiFlash config so it won't fail to synchronize.
Tests 
- No code (Tests should be tested by what?)

Cherry-pick #367 and #358 to 3.1

---

README.md
pkg/backup/client.go
pkg/backup/safe_point.go
pkg/task/backup.go

Currently, we just set the service GC safe point when writing SST files, but not when checksumming.
If checksum time expires 5min (the service safe point lifetime) plus the TiDB GC lifetime, we might meet "GC life time is shorter than transaction duration" error.
I moved the logic of setting GC safe point into another goroutine, which will set the service safe point every (1/5 service safe point lifetime).
This goroutine will be canceled by context.
Tests 
Though this test can be automatized by fail points, if we did so, our ingratiation test time will grow to 15 mins+, which is hard to accept. 
Firstly, we insert fail point at here:    
Then, we run current master branch with fail point:
After fixed, we can finish the backup:
- Fix a …

Set safe point at background

---

go.mod
pkg/backup/client.go
pkg/backup/safe_point.go
pkg/backup/schema.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/utils/worker.go

cherry-pick #402 and #396 
- Improve parallel processing power when backing up a large database with many regions.
- Fix a bug that may cause failed to backup when dataset is too large and GC lifetime is too brief.

cherry pick #402 and #396 to release 4.0.

---

pkg/restore/client.go
pkg/restore/util.go
pkg/task/restore.go
pkg/utils/worker.go

Currently, DDLs are send to TiDB cluster sequently, if we were the DDL owner, that is fine: we can execute this DDL immediately, and return very fast.
But we are not, and probably cannot. Then things getting bad, we **must** block and waiting our DDL job pushed to the queue, and executed by owner, then we can send next DDL. Even during waiting time, we can push more DDLs into the DDL job queue.
This PR make `GoCreateTabels` send create table jobs into DDL queue concurrently.
we change `GoCreateTables` and make it use below strategy to create tables:
1. if provided a `dbPool`, use this DB pool to execute DDLs concurrently.
2. if not, roll back to old version: send DDL sequentially.
Tests 
- Integration test (`br_300_small_tables`)
- Manual test
We test it locally, by a 300 table, per table …

cherry-pick (#377) to release-4.0

---

pkg/backup/client.go
pkg/restore/db.go
pkg/utils/schema.go

Fix CI failure after [tidb#18326](https://github.com/pingcap/tidb/pull/18326)
We don't try to restore auto ID for tables that don't need it.
Tests 
- fix a bug that causes, we will restore auto id even the table doesn't has it.

restore: don't restore auto id if the table doesn't has it.

---

pkg/backup/client.go

#396 made a little mistake, which make `last backup finish time - now` become backup time spent, and will lead to backup time become negative.
Tests 

Fix the problem that backup time may be negative

---

cmd/backup.go
cmd/cmd.go
go.mod
go.sum
pkg/backup/client.go
pkg/gluetidb/glue.go
pkg/restore/client_test.go
pkg/restore/db_test.go
pkg/task/backup.go
pkg/task/backup_raw.go
tests/br_db/run.sh

cherry-pick #404, #405, #406 and #421 to release 4.0

---

pkg/backup/push.go
pkg/backup/safe_point.go

fix #403
move some non-fatal error log into warn level
Tests 
- No code
- turn down some non-fetal error logs to warn level.

backup: move some non-fatal error log into warn level

---

pkg/conn/conn.go

Some times the version info can be lost (e.g. when build br with `go build` directly, instead of `make build`), at that time, the error message is confusing: 
```
None is not in dotted-tri format.
```
In all conditions when we failed to run checksum, we add a hint that "we can use `--check-requirements=false` to skip the version checker."
Tests 
1. run `go build -o bin/br` directly.
2. execute `br`.

Add a hint when running on incompatible cluster

---

pkg/backup/safe_point.go
pkg/task/backup.go

- Safe point keeper now will enable safe point at begin.
- Safe point keeper will show warning if safe point exceeds last backup TS.
- Use a random service safe point suffix so concurrently run BR won't conflict (even few people wants do such... , a little... insane thing).
See above.
Tests 
See #402, this PR is just some enhance.
- no release note

fix some design of safe point keeper

---

pkg/conn/scheduler_utils.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/task/restore.go
pkg/task/restore_raw.go
pkg/utils/pd.go
tests/br_other/run.sh

fixed #412.
Firstly, we extract the logic of removing schedulers to `conn` package, as a method of `conn.Manager`.
Then, we add a flag that controls whether to remove scheduler when backing up.
Finally, we call the extracted method on backup if the flag is set. 
Tests 
- Add an option that can be used to speed up backing up by changing some cluster config.

[cherry-pick] remove scheduler(#426)

---

pkg/backup/client.go

If we execute Backup SQL in TiDB, it won't set gcttl to default 5m. this will cause error
`'non-positive interval for NewTicker'`
Set gcttl to 5m in task `runbackup`
Tests 
use TiDB not include this commit:
```
mysql>  backup database * to 'local:///tmp/backup2';
ERROR 1105 (HY000): non-positive interval for NewTicker
```
use TiDB with this commit:
```
mysql> backup database * to 'local:///tmp/backup1';
+----------------------+------+--------------------+---------------------+---------------------+
| Destination          | Size | BackupTS           | Queue Time          | Execution Time      |
+----------------------+------+--------------------+---------------------+---------------------+
| local:///tmp/backup1 |    0 | …
```

backup: set gcttl to 5m if gcttl not set in TiDB

---

pkg/task/backup.go
pkg/task/restore.go

The only common entrance of BR binary and BR in TiDB is task.RunXXX.
and we should adjust related config in this function for both binary and TiDB 
Add `adjustBackupConfig` for task.RunBackup
Add `adjustRestoreConfig` for task.RunRestore
Tests 

common: adjust config in task RunBackup/RunRestore

---

pkg/task/restore.go

cherry-pick #448 to release-4.0 
In SQL restore. we choose one session to execute SQL, 
so we can't simple use dbPool to create table concurrently.
In restore. if we are using SQL `glue.OwnerStorage()` will return false. 
so we use this condition to tell whether we should make dbPool or not.
Tests 
test will include in https://github.com/pingcap/tidb/pull/18993
Code changes
Side effects

brieSQL: fix multi-thread panic during SQL restore (#448)

---

pkg/checksum/executor.go

Fix SEGFAULT during backup, close #450 . 
Do not pass a nil pointer to `distsql.Checksum`.
Tests 
- Fix the issue that checksum could SEGFAULT during backup.

checksum: fix SEGFAULT during backup

---

pkg/storage/gcs.go
pkg/storage/local.go
pkg/storage/noop.go
pkg/storage/parse.go
pkg/storage/s3.go
pkg/storage/s3_test.go
pkg/storage/storage.go

part of https://github.com/pingcap/ticdc/pull/826, to unify all s3 related api in the same repo. we decide to put new s3 api which ticdc needed into br.
move ticdc s3 api in br
Tests 

add s3 api to adapt cdc log

---

pkg/storage/gcs.go
pkg/storage/local.go
pkg/storage/noop.go
pkg/storage/s3.go
pkg/storage/s3_test.go
pkg/storage/storage.go
pkg/utils/math.go
pkg/utils/math_test.go

cherry-pick #446 to release-4.0
Tests 
- Unit test
- No code
Code changes
Side effects
-

storage: extend the `ExternalStorage` interface and implements (#446)

---

pkg/storage/gcs.go
pkg/storage/local.go
pkg/storage/noop.go
pkg/storage/s3.go
pkg/storage/storage.go

Signed-off-by: glorv <glorvs@163.com>
Use file path in ExtrenalStorage method `WalkDir` and `Open`
Tests 
- Unit test
- No code
Code changes
Side effects

storage: use path in WalkDir and Open

---

pkg/storage/gcs.go
pkg/storage/local.go
pkg/storage/noop.go
pkg/storage/s3.go
pkg/storage/storage.go

resolve https://github.com/pingcap/br/pull/463#discussion_r474395528 
move `dir` `listCount` parameters into context
update WalkDir api
Tests 
- No code

storage: update WalkDir

---

pkg/backup/client.go

resolve https://github.com/pingcap/br/issues/470
we calculate duplicate in backup summary log. the first time is in BackupRange, and the second time is in checksum, we should remove the second one because not every backup task starts with checksum.
Tests 
before this PR in v4.0.4:
```
[2020/08/25 10:36:22.567 +08:00] [INFO] [collector.go:60] ["Table backup Success summary: total backup ranges: 1, total success: 1, total failed: 0, total take(s): 0.13, total kv: 71996, total size(MB): 72.23, avg speed(MB/s): 547.18"] ["backup checksum"=127.091977ms] ["backup fast checksum"=217.299µs] ["backup total regions"=1] [BackupTS=418990779862614018] [Size=530514]
```
after this fix:
```
[2020/08/25 10:33:04.525 +08:00] [INFO] [collector.go:60] …
```

backup: remove duplicate kv size summary collect

---

pkg/backup/client.go
pkg/task/backup.go
tests/br_incremental_index/run.sh

resolve https://github.com/pingcap/br/issues/454
we shouldn't filter schemas that doesn't have backup files. because the schema may have ddl jobs to do.
Tests 
Code changes
Side effects

integration_test: fix br_incremental_index test not stable

---

pkg/restore/client.go

Fix the issue that switch to import mode not work at first 5 minutes.
do switchToImportMode at first.
Tests 
There is no "switch to import mode" log if we finish restore in 5 minutes.
- Fix the issue that switch to import mode not work at first 5 minutes.

restore: switch mode immediately when restore start.

---

go.mod
go.sum

Fix CI failed with "tikv timeout"
Currently, when a lock resolved, the continuing proto message would be incorrect(for unknown reason).
We would get errors like:
```
grpc: failed to unmarshal the received message proto: wrong wireType = 2 for field UseAsyncCommit
```
After updating `kvproto`, the problem seems resolved magically(!).
Tests 

Fix CI failed with "tikv timeout"

---

pkg/restore/client.go
pkg/restore/import.go
pkg/summary/collector.go

implement #478 
We make serval changes to make the log of time cost correct:
1. collect kv and size each time of importing.
https://github.com/pingcap/br/blob/d9d6207c0aa7bad470093683427338053435e1ba/pkg/restore/import.go#L328-L331
2. a log of real time cost is added to the summary.
3. collect the success unit when checksumming, so the total cost field would be (the time of restoring + the time of checksumming) instead of just the time of restoring.
Tests 
- Add real time cost to log.

summary: add real time cost to log collector

---

cmd/restore.go
pkg/restore/client.go
pkg/restore/import.go
pkg/restore/pipeline_items.go
pkg/restore/util.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/task/common.go
pkg/task/restore.go
pkg/task/restore_raw.go
pkg/utils/pd.go
pkg/utils/version.go
pkg/utils/version_test.go

Historically, we must remove all TiFlash nodes or the restore progress sticks. How ever, for now, TiFlash can support all RPCs BR needs.
The code handling TiFlash nodes costs and can bring many useless logs. It's time to remove it.
I removed all (I hope) logic removing the TiFlash nodes.
Tests 
- BR doesn't remove TiFlash nodes anymore.

*: don't remove tiflash more.

---

pkg/storage/local.go
pkg/storage/local_test.go

fix local storage walk dir return invaild file size for soft link files
Tests 
- Unit test
- No code
Code changes
Side effects
-

storage: fix walk dir file size

---

pkg/backup/client.go
pkg/restore/import.go

Check if pd.GetRegion return region value is nil to avoid panic
Tests 
- Unit test
- No code
Code changes
Side effects
-

backup,restore: fix panic when pd.GetRegion return nil

---

pkg/backup/client.go

record store id when `cli.Recv()` failed, to reduce to the cost of debug TiKV node.
add store id on return error
Tests 
- No code

error: record store id when backup connection failed

---

pkg/task/common_test.go
pkg/task/restore.go
tests/br_db/run.sh
tests/br_full/run.sh

half-fixed [tidb#20037](https://github.com/pingcap/tidb/issues/20037)
we restore the changed config after restoring.
Tests 
- fix a bug that caused the TiDB config changed after restoring

restore: restore tidb config after restoring

---

pkg/task/common_test.go
pkg/task/restore.go
tests/br_db/run.sh
tests/br_full/run.sh

cherry-picking #509
=== 
half-fixed [tidb#20037](https://github.com/pingcap/tidb/issues/20037)
we restore the changed config after restoring.
Tests 
- fix a bug that caused the TiDB config changed after restoring

[cherry-pick] restore: restore tidb config after restoring(#509)

---

pkg/backup/client.go
pkg/backup/push.go
pkg/conn/conn.go
tests/br_full/run.sh

reset connection when tikv is down during backup.
add reset function for client.Mgr
Tests 

backup: add retry when tikv is down

---

pkg/backup/client.go
pkg/backup/push.go
pkg/conn/conn.go
tests/br_full/run.sh

cherry-pick #508 to release-4.0
reset connection when tikv is down during backup.
add reset function for client.Mgr
Tests 

[cherry-pick] backup: add retry when tikv is down (#508)

---

pkg/storage/parse.go
pkg/storage/parse_test.go

1. If we don't specify for `rawURL`, it will return an error. 
2. If we use a relative path for `rawURL`, it will return a wrong path.
1. adjust rawURL to local path if no u.Schema is given
2. Use `filepath.Abs` to make sure path is transferred.
Tests 
- Unit test

adjust rawURL to local path if no u.Schema is given

---

pkg/task/restore_raw.go
tests/br_rawkv/run.sh

When we don't provide the `concurrency` config in raw restoring, the `file` worker pool size would be 0, and then block all the restore process.
probably relative to #534 
Set concurrency to default when no config here.
Tests 
- Fixed a bug that caused restoring blocks when no `concurrency` provided.

raw_restore: set concurrency to default when no config here

---

cmd/validate.go
pkg/conn/conn.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/task/common.go
pkg/task/restore.go
pkg/task/restore_log.go
pkg/task/restore_raw.go

Currently, keepalive time and timeout in both TiKV and TiDB are configurable. According to the `keepalive.ClientParameters`:
> Make sure these parameters are set in coordination with the keepalive policy on the server, as incompatible settings can result in closing of connection.
We should make those variables in BR configurable too so when they are changed, BR won't make confusing behavior.
Added two flags: `grpc-keepalive-time` and `grpc-keepalive-timeout`.
Tests 
- Integration test 
- Added config `grpc-keepalive-time` and `grpc-keepalive-timeout`.

conn,task: add config about keepalive

---

pkg/backup/client.go
pkg/restore/split_client.go
pkg/task/backup.go
pkg/task/restore.go
pkg/utils/safe_point.go
pkg/utils/safe_point_test.go

br encountered the `GC life time is shorter than transaction duration` error. because of this [check](https://github.com/pingcap/tidb/blob/180c02127105bed73712050594da6ead4d70a85f/store/tikv/kv.go#L186-L190) in restore checksum.
Add `StartServiceSafePointKeeper` for restore procedure just like backup.
Tests 
- No code
- Fix the issue that restore failed when restore checksum task time more than gc life time.

checksum: fix checksum gc life time excceed issue

---

pkg/restore/split_client.go
pkg/task/common.go
pkg/task/common_test.go
tests/br_full/run.sh
tests/br_tls/run.sh

fix #536 
We check PD URLs and strip prefix before running.
Tests 
- Unit test
- Fix a bug that caused failure when using `--pd` with urls starts with `http` or `https`.

*: strip PD urls with http or https

---

Makefile
main.go
pkg/gluetikv/glue.go
pkg/pdutil/pd.go
pkg/restore/batcher.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/task/restore.go
run-test.sh
tests/br_other/run.sh

fix #557
This PR also added a guard for the `glue.Progress` implement, to prevent the `send on close channel` panics.
see #557 
Tests 
- Fixed a bug that caused BR won't do cleanup tasks when receiving SIGTERM.

*: when cleaning up, use isolated context

---

Makefile
main.go
pkg/backup/client.go
pkg/backup/push.go
pkg/gluetikv/glue.go
pkg/pdutil/pd.go
pkg/restore/batcher.go
pkg/restore/batcher_test.go
pkg/restore/client.go
pkg/restore/client_test.go
pkg/restore/pipeline_items.go
pkg/restore/util.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/task/restore.go
pkg/task/restore_log.go
pkg/task/restore_raw.go
pkg/utils/logging.go
run-test.sh
tests/br_other/run.sh
tests/br_tiflash/run.sh

cherry-picking #452, #427, #559 to release-4.0.
N/A
Tests 
- Unit test
- No code
- (See PRs #452, #427, #559)

*: cherry-picking some PRs for v4.0.8

---

cmd/restore.go
pkg/cdclog/decoder.go
pkg/cdclog/puller.go
pkg/restore/log_client.go
pkg/storage/local.go

cherry-pick #568 to release-4.0
Fix serval bugs about restore cdclog feature.
1. Fix the issue that when restore binary/varbinary field will lost bytes.
2. Fix the issue that wrong events filtered by ts range filter.
3. Fix panic by add the length check for cdclog data.
4. Change the hidden parameter to the experimental feature.
5. Add more log for debug.
Tests 

cdclog: Fix serval bugs about restore cdclog feature. (#568)

---

pkg/backup/push.go
pkg/restore/batcher.go
pkg/restore/pipeline_items.go
pkg/restore/split.go

Tests 
- Unit test
- No code
Code changes
Side effects
-

Spelling error in code comment

---

pkg/restore/client.go
pkg/restore/client_test.go
pkg/restore/import.go
pkg/restore/log_client.go
pkg/task/restore.go
pkg/task/restore_log.go
pkg/task/restore_raw.go

#545 added the config value of keepalive, but it has forgotten the restore part(!).
Apply the config to restoring.
Tests 
- Unit test
(If the old tests passed, then the default config should be applied.)
- Fix a bug that causes the keepalive configs don't apply to restore.

restore: set configed keepalive for restore

---

pkg/storage/s3.go

https://github.com/pingcap/dumpling/issues/180
increase maxRetries from 3 to 6
Tests 
- Unit test
Side effects

storage: increase aws maxRetries request config from 3 to 6

---

pkg/gluetikv/glue.go
pkg/summary/collector.go
pkg/summary/collector_test.go
pkg/utils/progress.go
pkg/utils/progress_test.go

dumpling wants to use collector. But the logger is different.
export log exporter for dumpling to specify its own logger.
Tests 
- Unit test
Code changes

summary/: export new log collector

---

cmd/debug.go
docker-compose.yaml
pkg/backup/client.go
pkg/conn/conn.go
pkg/logutil/logging.go
pkg/restore/client.go
pkg/restore/import.go
pkg/restore/range.go
pkg/restore/split.go
pkg/restore/util.go
pkg/rtree/rtree.go

Reduce unnecessary stack trace in warning logs.
Tests 
- Unit test

*: reduce unnecessary error stack trace

---

pkg/pdutil/pd.go
pkg/pdutil/pd_test.go

current parse pd version will failed. this bug is introduced in #592.
add strings.Trim before parse version
Tests 
- Unit test

pd: fix parse version

---

pkg/restore/split.go
pkg/restore/split_client.go

try to resolve https://github.com/pingcap/br/issues/634.
add check when scanRegions return empty leader but have peer.
Tests 
Code changes
Side effects

pd: add check when leader is empty

---

tests/_utils/run_services

br_tls recently almost always fail because TiKV cannot restart due to occupied port.
1. Change `stop_service` to first gracefully stop through a SIGHUP, before actually doing SIGKILL.
2. Insert some sleep to ensure OS has time to reap the ports from the process corpses.
3. Increase TiKV wait time for `start_services_with_tls` from 60s to 80s to workaround a certain bug caused by PD dashboard initialization which makes PD idle for 1 minute.
Tests 
Code changes
Side effects

tests: fix br_tls failure and make stop_services more robust

---

pkg/pdutil/pd.go
pkg/pdutil/pd_test.go
tests/_utils/run_services
tests/br_log_restore/run.sh
tests/br_other/run.sh

Set `max-pending-peer-count` to a large value (math.MaxInt32) during restore to avoid scatter regions failed due to pending peer filter.
Tests 
- No code
Code changes
Side effects
- Enlarge pd `max-pending-peer-count` during restore

pdutil: set max-pending-peer-count to a large value in RemovePdScheduers

---

pkg/storage/gcs.go
pkg/storage/gcs_test.go
pkg/storage/parse.go
pkg/storage/parse_test.go
tests/br_log_restore/run.sh

backup meta file out of backup directory in gcs storage.
ensure gcs prefix endwith "/"
Tests 
- Unit test
before:
after:
- Fix the issue that write backup meta file out of backup directory in gcs storage.

gcs: fix wrong path of gcs prefix

---

tests/br_shuffle_leader/run.sh
tests/br_shuffle_region/run.sh

Fix integration test error by pd-ctl does not support -d parameter anymore.
This error may be cause by  https://github.com/tikv/pd/pull/3337, but seems pd-ctl does not support -d for a long time. (don't know why, but -d seems to always have no effect)
Tests 
Code changes
Side effects
- No Release Note

test: remove the -d  parameter since pd-ctl doesn't support it anymore

---

pkg/backup/client.go
pkg/backup/schema_test.go
pkg/restore/client.go

also improved some logs
Part 1 of #679. 
If the stats is broken, we just log and skip it instead of bailing out.
Tests 
- Unit test
Code changes
Side effects
- Failing to backup statistics is no longer fatal.

backup: dump stats to json should not be fatal

---

cmd/cmd.go
tests/br_other/run.sh

In https://github.com/pingcap/br/pull/653, we added the `redact-log` parameter.
The redact log parameter name is different from TiKV's and PD's.
https://github.com/tikv/tikv/blob/master/etc/config-template.toml#L846
In TiKV it's `redact-info-log` configuration in config file.
https://github.com/tikv/pd/blob/master/server/config/config.go#L1373
In PD it's `redact-info-log` configuration in config file.
Change `redact-log` to `redact-info-log`.
Tests 
- Unit test
Side effects

cmd/: change redact log parameter name

---

cmd/backup.go
cmd/restore.go
pkg/task/backup.go
tests/br_full_ddl/run.sh

Disable backup stats by default. because of
1. DumpStatsToJson is not stable
2. It increases memory usage may cause BR OOM
1. set `cfg.IgnoreStats` default to true
2. if `cfg.IgnoreStats` is true, set `statsLease` to -1
Tests 
- Disable backup stats by default.

stats: disable stats by default

---

Makefile
tests/br_gcs/oauth.go
tests/br_gcs/oauth.py
tests/br_gcs/run.sh

Remove python code in tests.
Change flask OAuth server to go code.
Tests 

test: remove python code 

---

metrics/grafana/br.json

Many users(come from DBaaS、operator、tiup) monitor multiple TiDB clusters in one Grafana, this PR make Grafana dashboards support multiple clusters and not affect single cluster usage. Cluster variable is hidden by default.
- add a tidb_cluster label in all expr
- add cluster variable in Grafana templating
How it Works:
load it to your Grafana :))
Single Cluster:
No change
Multiple Cluster:
Construct a label that can uniquely identify the cluster. in tidb_operator, you can use {namespace}-{cluster_name} as your {tidb_cluster} variable.
add this configuration to your prometheus config
```
relabel_configs:
- source_labels:
- namespace
- name
separator: "-"
target_label: tidb_cluster
```
Tests
- No code
Code changes
- Has configuration change
- Has HTTP API interfaces change (Don't forget to …

grafana dashboards support multiple cluster

---

metrics/grafana/br.json

The latest version of tidb-operator will use the instance name as the cluster label. The previous expression uses the cluster label got the value of the tidb_cluster variable. It will cause Grafana can not to display the data.
Tests 
- No code
Code changes
Side effects
- No effects

metrics: use tidb_cluster label get variable values

---

cmd/cmd.go
cmd/debug.go
pkg/backup/client.go
pkg/kv/kv.go
pkg/kv/kv_test.go
pkg/logutil/logging.go
pkg/logutil/logging_test.go
pkg/logutil/redact.go
pkg/redact/redact.go
pkg/redact/redact_test.go
pkg/restore/batcher.go
pkg/restore/batcher_test.go
pkg/restore/client.go
pkg/restore/import.go
pkg/restore/log_client.go
pkg/restore/pipeline_items.go
pkg/restore/range.go
pkg/restore/split.go
pkg/restore/split_client.go
pkg/restore/util.go
pkg/rtree/logging.go
pkg/rtree/logging_test.go
pkg/rtree/rtree.go
pkg/task/restore.go
tests/br_key_locked/locker.go

*: restore: more log for split region
It helps investigating https://github.com/pingcap/br/issues/709.
Tests 
- Unit test
Code changes
Side effects

*: refine logs

---

pkg/restore/import.go
tests/br_rawkv/client.go
tests/br_rawkv/run.sh

cherry-picks https://github.com/pingcap/br/pull/201 to release-4.0
---
This PR fixes the issue that rawkv restore's end key is incorrectly inclusive when restoring partial of backed up data. See https://github.com/tikv/tikv/issues/7163
This PR adds is_raw_kv field to DownloadRequest and adds end_key_exclusive field to SstMeta. For SST files that contains the restoring end key in its range, it will cut the file's end key to the restoring endKey, and set end_key_exclusive.
Tests 
- Unit test
Code changes
- Added is_raw_kv to kvproto `DownlaodRequest`
- Added end_key_exclusive to kvproto `SstMeta`
Side effects
\-
- release-3.1 and release-4.0
* Fix the issue that in rawkv …

Fix the issue that rawkv restore's end key is incorrectly inclusive when restoring partial of backed up data (#201)

---

pkg/utils/schema.go
pkg/utils/schema_test.go

Speed up LoadBackupMeta.
Cc https://github.com/pingcap/br/issues/705
Manually tested with 39k tables, it improves fast checksum about 53 times.
<details> <summary>Benchmark results</summary>
```
[2021/02/19 14:50:58.551 +08:00] [INFO] [collector.go:60] ["Full backup Success summary: total backup ranges: 117738, total success: 117738, total failed: 0, total take(Full backup time): 2m43.027476154s, total take(real time): 23m31.342884193s, total kv: 117738000, total size(MB): 11298.47, avg speed(MB/s): 69.30"] ["backup checksum"=18.410789857s] ["backup fast checksum"=19m20.755603256s] ["backup total regions"=117824] [BackupTS=423025980821995522] [Size=4608796580]
[2021/02/19 16:29:03.509 +08:00] [INFO] [collector.go:60] ["Full backup Success summary: total backup ranges: 117738, total …
```

pkg/utils: speed up LoadBackupMeta

---

tests/br_s3/run.sh

create bucket only once and remove bucket via mc to fix CI failure
```
[2021-03-02T08:25:27.024Z] + bin/mc mb --config-dir /tmp/backup_restore_test/br_s3 minio/mybucket
[2021-03-02T08:25:27.024Z] mc: <ERROR> Unable to make bucket `minio/mybucket`. The specified bucket does not exist
```
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5038/pipeline/#step-987-log-442
Tests 

tests: create bucket only once and remove bucket via mc

---

tests/lightning_checkpoint_engines/run.sh

Fix lightning integration test `checkpoint_engines` by clean up useless files.
Close #768 
#768 is caused by when lightning was killed after import engine success but before engine clean up, files in pebble db directory are not fully deleted, thus open pebble db with the remaining files may return unexpected errors.
Tests 
- Run target integration test in a local environment more than 100 times and this error didn't appear. 
- No code
Code changes
Side effects

tests: fix lightning integration test checkpoint_engines

---

tests/br_gcs/run.sh

I happened to meet an unexpected port occupation in CI env.
```
[jenkins@test-go1130-memvolume-23ljz agent]$ lsof -i :5000
COMMAND   PID    USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
oauth   17595 jenkins    3u  IPv6 1974781415      0t0  TCP *:commplex-main (LISTEN)
[jenkins@test-go1130-memvolume-23ljz agent]$ pwdx 17595
17595: /home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br
```
use `killall -9` to kill `oauth`
Tests 
- Unit test

tests: fix oauth process is not killed in gcs test

---

tests/br_log_restore/run.sh
tests/br_s3/run.sh
tests/lightning_s3/run.sh

Minio server may be slow to start, so extend wait time to stable tests.
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5239/pipeline/#step-1448-log-88
The test above shows starting a minio server may require 14 seconds or more.
Close #799 
Tests 

tests: extend minio wait time to stable minio slow start

---

pkg/kv/session.go
pkg/kv/session_test.go
pkg/lightning/backend/session.go
pkg/lightning/backend/session_test.go

This PR removes setOption and delOption from the implementation of the transaction in br
- Unit test

pkg/kv:remove set/delete option from transaction

---

pkg/lightning/backend/local.go
pkg/lightning/config/config.go
tidb-lightning.toml

Disable local-writer and disk-quota by：
- Set check-disk-quota interval to 0 by default to disable disk-quota
- Replace local-writer `AppendRows` function with the original write-batch approach.
Tests 
- Unit test
- No code
Code changes
Side effects

pkg/lightning: temporarily disable local-writer and disk-quota

---

pkg/lightning/backend/backend.go
pkg/lightning/backend/backend_test.go
pkg/lightning/backend/importer.go
pkg/lightning/backend/importer_test.go
pkg/lightning/backend/local.go
pkg/lightning/backend/local_test.go
pkg/lightning/backend/tidb.go
pkg/lightning/backend/tidb_test.go
pkg/lightning/config/config.go
pkg/lightning/lightning.go
pkg/lightning/lightning_test.go
pkg/lightning/restore/restore.go
pkg/lightning/restore/restore_test.go
pkg/mock/backend.go
tests/lightning_checkpoint/run.sh
tests/lightning_disk_quota/config.toml
tidb-lightning.toml

Lightning's Local Backend may OOM because some cache are too aggressive.
(Split off from #815).
1. Make the engine's mem table size configurable (keep default at 512 MiB)
2. Make the local writer's mem table size configurable (reduce default from 512 MiB to 128 MiB)
3. Reduced capacity of `LocalWriter.kvsChan` from 1024 to 16. Originally this will make Lightning retain 1024 × (region-conc) × (encoded-kvs) in the channel buffer, which can hold over 3 GiB.
Tests 
- Unit test
Code changes
Side effects
- Added configurations `tikv-importer.engine-mem-cache-size` and `tikv-importer.local-writer-mem-cache-size` to tune between memory usage and performance.

lightning: reduce memory use

---

pkg/lightning/restore/restore.go

Fix the bug that lightning may ignore context cancel error and lose data.
Close #855.
In the failed `lightning_checkpoint_chunks` integrations tests, there are logs as follows:
```
[2021-03-13T13:05:59.989Z] [2021/03/13 21:05:39.395 +08:00] [INFO] [restore.go:2553] ["restore file completed"] [table=`cpch_tsr`.`tbl`] [engineNumber=0] [fileIndex=3] [path=cpch_tsr.tbl.4.sql:0] [readDur=1.161606ms] [encodeDur=2.307684ms] [deliverDur=0s] [checksum="{cksum=0,size=0,kvs=0}"] [takeTime=4.021432ms] []
```
Note the deliverDur` is 0, this means the `deliverResult` is an object with the default parameter which is caused by reading from a closed channel.
Tests 
- Unit test
- No code
Code changes
Side effects
- Need …

pkg/lightning: fix chunk restore may ignore error if ctx is canceled

---

pkg/backup/client.go
pkg/restore/client.go
pkg/storage/gcs.go
pkg/storage/storage.go
pkg/task/backup.go
pkg/task/backup_raw.go
pkg/task/common.go
pkg/task/restore.go
pkg/task/restore_log.go

This helps with local testing of GCS and might also be useful in other contexts.
With gcs-fake-server running backup can be performed with these options:
```
br --gcs.endpoint http://localhost:4443/storage/v1 \
--no-credentials --send-credentials-to-tikv=false --skip-check-path
```
Tests
- Manual test (see above)
Code changes
- Has exported function/method change: no
- Has exported variable/fields change: only additions
- Has interface methods change: no
- Has persistent data change: no
Side effects
- ?
- Add testing options --no-credentials and --skip-check-path

br flags: --no-credentials and --skip-check-path

---

tests/br_full_ddl/run.sh

Skip compare 'correlation' filed because the backup and restore float64 output precision may not be the same.
Example:
```
backup:  [correlation=-0.008183768183768184]
restore: [correlation=-0.008184]
```
Tests 
Code changes
Side effects

test: skip 'correlation' field when compare statistics

---

pkg/lightning/lightning.go
pkg/storage/compress_test.go
pkg/storage/local_test.go
pkg/storage/parse.go
pkg/storage/parse_test.go
pkg/storage/writer_test.go

Lightning is different from BR and Dumpling that `force-path-style` is false by default. This is because both BR and Dumpling reads the storage URL through `(*BackendOptions).ParseFromFlags` which sets `ForcePathStyle` to true:
https://github.com/pingcap/br/blob/0b223bc5358cbe7ef6a54ad10fdd7aca81bf547f/pkg/storage/s3.go#L203
but such adjustment is absent from Lightning.
We set the default `ForcePathStyle` to true inside `storage.ParseBackend` so Lightning, starting with the default backend options, will also use `force-path-style=true` by default.
Also fixed the unit tests on Windows.
Tests 
- Unit test
Code changes
Side effects
* Lightning uses `force-path-style=true` by default, instead of `force-path-style=false`.
- Then importing from …

Make Lightning S3 use force-path-style=true by default 

---

pkg/restore/client.go
pkg/restore/client_test.go
pkg/restore/util_test.go
pkg/task/restore.go

Fix #931
Set TiFlash replica to nil when restore cluster's TiFlash nodes are not satisfied.
Tests 
- Unit test
- Fix the issue when BR restore TiFlash Info not satisfied with the cluster.

restore: set tiflash replica to nil when tiflash node is not satified

---

Makefile

In macOS, `make` would stick at checking backuppb, with a warning 'recursive search from stdin.'
When `-R` provided but no file provided, `grep` of macOS will wait for read from stdin, omit the `-R` flag. This PR make the make script provide the search target explicitly.
But `grep` of linux would implicit use current directory to search, so this bug won't appear in linux.
Tests 

makefile: fix the problem that `make` stuck in macOS

---

pkg/utils/schema.go

Fix the false 'analyze table failed' error.
Before, we store `new(handle.JSONTable)` into `Table.Stats` in any condition, which would make the guard at `restore.go` invalid.
Now, store `nil` to `Table.Stats` default.
Tests 
Run `br_gcs`, no error anymore.
- Fix a bug that caused restore would always report a false error

restore: fix false analyze failed error

---

pkg/lightning/backend/backend.go
pkg/lightning/backend/importer/importer.go
pkg/lightning/backend/local/local.go
pkg/lightning/backend/local/local_test.go
pkg/lightning/backend/noop/noop.go
pkg/lightning/backend/tidb/tidb.go
pkg/lightning/restore/restore.go
pkg/lightning/restore/restore_test.go
pkg/mock/backend.go

Return error at check-requirement if tidb cluster <= "v4.0.4" and some table contains tiflash replicas.
close #965
Tests 
- Unit test
- No code
Code changes
Side effects
- Make return error more user-friendly when lightning load data into tables with TiFlash replica but cluster version is too old.

pkg/lightning: check compatibility with  tiflash

---

Makefile

Fix the issue that makes would build the wrong version tag when execute it not in the `release` branch.
update the branch check conditions in MakeFile
Tests 
- Fix the issue that makes would build the wrong version tag when execute it not in the `release` branch.

makefile: fix the issue that build the wrong version when not in release branch

---

Makefile

Fix the issue that makes would build the wrong version tag when execute it not in the `release` branch.
update the branch check conditions in MakeFile
Tests 
- Fix the issue that makes would build the wrong version tag when execute it not in the `release` branch.

makefile: fix wrong release version build

---

pkg/lightning/restore/restore_test.go
pkg/lightning/restore/tidb.go
pkg/lightning/restore/tidb_test.go

Fix the wrong table count in the `progress` log like following:
```
[2021/04/12 14:26:43.837 +08:00] [INFO] [restore.go:1026] [progress] [total=0.0%] [tables="0/2 (0.0%)"] [chunks="0/99 (0.0%)"] [engines="0/2 (0.0%)"] [speed(MiB/s)=145.03058180393646] [state=preparing] []
```
There is only one table data in the source files but the pending tables count is 2. 
Calculate pending table count based on the tables in dbMetas instead of tables fetched from TiDB.
Tests 
- Unit test
Code changes
Side effects
- Fix the bug that the table count in the progress log is wrong

pkg/lightning: fix incorrect table counter

---

pkg/lightning/lightning_test.go
tests/lightning_checkpoint/run.sh

close #782 
- Do not run `lightning_checkpoint` with tidb backend because tidb backend's checkpoint can't guarantee exact once semantics if target table has no primary/unique key.
- Wait more time (0.5s -> 1.5s) for unit test `TestRunServer` to make it less possible to timeout.
Tests 
Code changes
Side effects

test: fix unstable integration test lightning_checkpoint

---

pkg/lightning/lightning_test.go

TestLightning `Runserver` checks error is `nil` in another goroutine.and the result is unstable because Teardown(`ctx.cancel()`) may happen before `Runserver` exit.
just like https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/9631/pipeline
remove this check. because the error is either `nil` or `context.cancel`.
Tests 
- Unit test

test: fix the unstable unit test 

---

go.mod1
go.sum1

Update TiDB.
go get github.com/pingcap/tidb@release-5.0
``` git-log
200d7f1a89c9e4c9c02f9d43d33d296e035fefbb table: initialize index.needRestoredData lazily (#24030) (#24032)
f385f88728f9e2cb7907ee7c46d4d4bd6b578ba3 store/tikv: support injecting customized failure to prewrite (#23432) (#24036)
90ec27c220e28051a29c0ac9a7d25a25eaaab8d4 session, executor: skip some frequent unstable test cases (#24003) (#24025)
f152069401a3df7e435c8a137240c8d1567b8543 *: collect transaction write duration/throughput metrics for SLI/SLO (#23462) (#23954)
c51c976ab2e2c4ee2aeb39d8560560539b22631f store, kv: Add information about async commit/1pc to tidb_last_txn_info (#23833) (#23868)
f3951ecc4e708cee5f546d39f8f2edda75abf6cc expression: Implementation of Vitess hashing algorithm. (#23493) (#23915) …
```

*: update TiDB

---

.github/workflows/compatible_test.yml
pkg/backup/client.go
pkg/backup/push.go
pkg/task/backup.go
pkg/task/backup_raw.go
tests/br_300_small_tables/run.sh
tests/br_db/run.sh

Solve https://github.com/pingcap/br/issues/1042
if backup ranges is more than 100, we can use range as the unit of progress.
Tests 
- Fix the issue that backup costs too much time to count progress units when backup lots of ranges.

backup: optimize progress update logic

---

Makefile

Fix make on macOS by correct regex.
Tests 
```
git tag v5.0.2
git checkout -b refs/tags/v5.0.2
make build
```

Makefile: fix version number on macOS

---

pkg/lightning/mydump/loader.go
pkg/lightning/mydump/loader_test.go
pkg/lightning/restore/restore.go

Restoring table schema raised wrong error messages.
https://github.com/pingcap/br/issues/969
Propagating the error out.
Tests 
- Unit test
Code changes
Side effects

lightning: fix wrong error message of restoring table

---

cmd/br/backup.go
cmd/br/cmd.go
cmd/br/restore.go
errors.toml
pkg/backup/client.go
pkg/backup/schema.go
pkg/backup/schema_test.go
pkg/errors/errors.go
pkg/gluetidb/glue.go
pkg/restore/systable_restore.go
pkg/task/common.go
pkg/task/restore.go
pkg/utils/schema.go
tests/br_full_ddl/run.sh
tests/br_full_index/run.sh
tests/br_systables/run.sh
tests/br_systables/workload

#872 and #679.
But this doesn't allow restore stats -- because the table IDs of the stats backed up are old table IDs, we need more efforts to rewrite them to make them take effect after the restoration.
This PR basically implemented https://github.com/pingcap/br/issues/679#issuecomment-762592254, with some difference:
- When the target table not exists, `RENAME TABLE temp.xxx TO mysql.xxx` would be used, for effectively restoring user tables created in `mysql` schema.
- The user interface is the `-f` (the table filter) flag. Users must specify each table they want to restore by the table filter syntax (e.g. `br restore full -f '*.*' -f '!mysql.*' -f 'mysql.usertable'` to restore `mysql.usertable`).
Tests 
- …

backup,restore: support backing up / restore system databases

---

pkg/pdutil/pd.go
pkg/pdutil/pd_test.go

This pr is cherry pick version of [#1088 ](https://github.com/pingcap/br/pull/1088) for release-4.0
When client send a request to pd failed due to some recoverable server faults or network issues, it is better to retry than to return error.
Add pd request retry logic on  `pdRequest` function in `pkg/pdutil/pd.go` file.
Tests 
- Unit test
Code changes
- No Release Note

pd: Add pd request retry logic (#1088)

---

.github/workflows/build.yml
Makefile
pkg/lightning/backend/local/local_freebsd.go
pkg/lightning/backend/local/local_unix.go
pkg/lightning/backend/local/local_unix_generic.go
pkg/lightning/common/storage_unix.go
pkg/lightning/lightning.go
pkg/lightning/restore/restore.go

The structs for `golang.org/x/sys/unix` on FreeBSD and Linux have different type for various members.
```
[dvaneeden@freebsd-tidb ~]$ for os in freebsd darwin linux; do echo $os; GOOS=$os go doc golang.org/x/sys/unix Statfs_t | grep Bsize; done
freebsd
Bsize       uint64
darwin
Bsize       uint32
linux
Bsize   int64
```
This adds a `pkg/lightning/backend/local/local_freebsd.go` file that is based on `pkg/lightning/backend/local/local_unix.go` but is using types that match FreeBSD for `rLimit.Cur` and `rLimit.Max`.
In `pkg/lightning/common/storage_unix.go` I fixed a minor incompatibility with `Bavail` of `Statfs_t`.
Tests 
Running `gmake build` on FreeBSD now works without errors and produces a binary.
```
[dvaneeden@freebsd-tidb ~/br]$ …
```

FreeBSD support

---

pkg/lightning/restore/tidb.go
tests/lightning_alter_random/run.sh

close #1104 
Tests 
Code changes
Side effects
- Fix the bug that lightning tidb backend cannot load any data when `autocommit` is disabled.

lightning: always enable `autocommit` in db connection

---

pkg/lightning/backend/kv/sql2kv.go
pkg/lightning/backend/kv/types.go
pkg/lightning/backend/noop/noop.go
pkg/lightning/backend/tidb/tidb.go
pkg/lightning/restore/restore.go
pkg/lightning/restore/restore_test.go
tests/lightning_checkpoint_parquet/run.sh

`panic: pebble: batch too large: >= 4.0 G`
sends kv batch every 96k.
Tests 
- Unit test
- Fix the issue that lightning panic due to batch kv greater than 4.0g.

lightning: fix encode kvs size greater than 4.0g caused pebble panic

---

pkg/lightning/backend/local/local.go
pkg/lightning/backend/local/localhelper.go
pkg/lightning/backend/local/localhelper_test.go
pkg/lightning/restore/restore.go

Let lightning return the actual error instead of return `context.Canceled`
- Retry split regions instead of direct return an error in `BatchSplitRegions`
- check parent's context cancel event to avoid direct returning when chunk routine fails.
Tests 
- Unit test
- No code
Code changes
Side effects

lightning: avoid ignore error when import data fails

---

pkg/task/backup.go

Signed-off-by: JmPotato <ghzpotato@gmail.com>
`GoTimeToTS()` from [varsutil.go#L469](https://github.com/pingcap/tidb/blob/c8bc701170165e82cc7893ab68523f9a2059a7e6/sessionctx/variable/varsutil.go#L469) is exactly the same as `GoTimeToTS()` in `oracle` pkg which is the original version and the right place it should belong to.
Use `oracle.GoTimeToTS()` instead of `variable.GoTimeToTS()`, and the latter will be removed in pingcap/tidb#24813.
Tests 
- Unit test
- pingcap/tidb#24766

pkg: use the GoTimeToTS() from oracle pkg

---

tests/run.sh

When we make integration test, an unbound variable error will raise.
Change `tests/run.sh`
In original version
```sh
for casename in $SELECTED_TEST_NAME; do
script=tests/$casename/run.sh
echo "*===== Running test $script... =====*"
INTEGRATION_TEST=1 \
TEST_DIR="$TEST_DIR" \
TEST_NAME="$casename" \
CLUSTER_VERSION_MAJOR="${CLUSTER_VERSION_MAJOR#v}" \
CLUSTER_VERSION_MINOR="$CLUSTER_VERSION_MINOR" \
CLUSTER_VERSION_REVISION="$CLUSTER_VERSION_REVISION" \
PD_ADDR="$PD_ADDR" \
TIDB_IP="$TIDB_IP" \
TIDB_PORT="$TIDB_PORT" \
TIDB_ADDR="$TIDB_ADDR" \
TIDB_STATUS_ADDR="$TIDB_STATUS_ADDR" \
TIKV_ADDR="$TIKV_ADDR" \
BR_LOG_TO_TERM=1 \
bash "$script" && echo "TEST: [$TEST_NAME] success!"
done
```
the previous assignment `TEST_NAME="$casename"` will not work for `echo "TEST:[$TEST_NAME] success!"` in …

test: fix integration test unbound variable error

---

tests/br_clustered_index/run.sh
tests/br_tikv_outage/run.sh

Key range in backup and checksum might be wrong at the same time(They are still the same) when the table use clustered index, which means checksum cannot find this error.
add row_count check for the test.

tests: add row count check for br clustered index tests

---

pkg/storage/storage.go

When we set `SkipCheckPath` to true, external local storage won't create a directory and will fail to create a new file.
Try `mkdirAll` even when `SkipCheckPath` is true.
Tests 
- Unit test
Code changes
Side effects

storage: mkdirAll for local storage even when SkipCheckPath is true

---

tests/_utils/run_services
tests/br_tikv_outage/run.sh

fix bug in issue #1158
for #1158 add sleep 1 to ensure tikv start up completely before restore
Tests 
- Unit test

tests/br: fix bug in issue #1158

---

.github/workflows/build.yml
.github/workflows/compatible_test.yml
CONTRIBUTING.md
README.md
docker/Dockerfile
go.mod1
go.sum1
pkg/storage/gcs.go
tests/up.sh
tools/go.mod
web/go.mod

The CI recently upgraded the Go compiler version to 1.16, but the test scripts and go.mod still assume 1.13. This PR changes them all to 1.16 to keep in sync with the CI.
Upgrade all references to Go 1.13 and 1.15 to 1.16.
Tests 
- No code
Code changes
Side effects

*: upgrade go version from 1.13/1.15 to 1.16

---

pkg/kv/kv.go
pkg/lightning/backend/kv/sql2kv.go
pkg/lightning/backend/kv/sql2kv_test.go

Fix the bug that lightning will got invalid auto_increment base if the corresponding auto_increment field is double/float.
```
[2021/06/05 13:37:03.227 +08:00] [INFO] [tidb.go:355] ["alter table auto_increment start"] [table=`db`.`table`] [auto_increment=4753151844738400257]
```
Tests 
- Unit test
- No code
Code changes
Side effects
- Fix the bug that lightning rebase wrong auto_increment base when the auto_increment field type is float or double.

lightning: fix id allocator base for double auto_increment field

---

pkg/lightning/mydump/region.go
pkg/lightning/mydump/region_test.go

close #1133 
don't return io.EOF error if split large csv meets EOF error.
Tests 
- Unit test
- No code
Code changes
Side effects
- Fix the bug that lightning returns EOF error when CSV file without '\r\n' at the last line and `strict-format = true`.

lightning: fix split larget csv EOF error

---

pkg/lightning/restore/meta_manager.go
pkg/lightning/restore/meta_manager_test.go
pkg/lightning/restore/restore.go

Fix the bug that if `post-restore.checksum = off` and table auto_increment base is not 0, lightning will panic due to checksumManager is nil. 
Avoid do pre-checksum if check is disabled.
Tests 
- Unit test
- No code
Code changes
Side effects

lightning: avoid do pre-checksum when checksum is disabled

---

go.mod1
go.sum1
tests/br_backup_empty/run.sh
tests/br_backup_version/run.sh
tests/docker_compatible_gcs/prepare.sh
tests/docker_compatible_gcs/run.sh
tests/docker_compatible_s3/prepare.sh
tests/docker_compatible_s3/run.sh

We have disabled some tests previously in order to update to client-go/v2.
- update tidb to latest master
- enable integration tests
Tests 

*: update tidb and enable integration tests

---

pkg/lightning/mydump/loader.go
pkg/lightning/mydump/loader_test.go
pkg/lightning/restore/restore.go

solve https://github.com/pingcap/br/issues/1221
lightning pre-check will print empty info when check skipped.
lightning may report a false-positive error when no-schema has deprecated.
skip print check template when --check-requirements if false
remove unnecessary check in setup after no-schema is deprecated.
Tests 
- Unit test

Lightning: skip print check template and remove unnecessary check

---

pkg/metautil/metafile.go
pkg/restore/db_test.go

solve https://github.com/pingcap/br/issues/1222
json unmarshal ddl bytes array failed, because we got an `[]` in reader.backupMeta.Ddls in v2 meta.
use reader.backupMeta.DdlIndexes to determine whether we are use v1 or v2 meta.
Tests 
- Unit test
- Fix the issue that incremental restore DDL failed when use meta v2 backups.

backup: fix ddl unmarshal error in meta v2

---

tests/br_tikv_outage/run.sh

shell stuck to wait file created by BR while BR is exited with failure status.
add a condition : when BR process is not alive, shell will jump out loop.

tests: fix shell stuck while br is exited with failure status

---

tests/lightning_disk_quota/config.toml
tests/lightning_disk_quota/run.sh

Reduce the time spent on test disk quota, which is reduced from about 20 minutes to 3 minutes.
Decrease sleep time in `SlowDownWriteRows` to 50 ms and  `check-disk-quota` in config file to 100ms.
Tests 
Code changes
Side effects

test: reduce the time spent on test disk quota

---

pkg/restore/client.go
tests/lightning_checkpoint_engines_order/run.sh

1. files will be empty, which cause to log info print empty content.
https://github.com/pingcap/br/blob/f0c1eb5188549489440cb9ae2eb371883cc7dc87/pkg/restore/client.go#L594
2. `lightning_checkpoint_engine_order` : there is an engine cleaned up lead to count 2 other than 3 which failed.
https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/4877/pipeline/84/
1. add temp variable
2. record all the existing engines into the file, and count the number of different engines
Tests 
- Unit test

restore: fix [files lost] in log info

---

pkg/storage/noop.go

When dumpling specify a noop uri, dumpling will panic.
Fix noop storage structures.
Tests 
- Unit test

storage: fix noop writer to help dumpling to do some tests

---

pkg/lightning/backend/local/local.go

A workaround for #1213.
Tests 
- Unit test
Code changes
Side effects
No release note.

lightning: fix panic in `nextKey`

---

pkg/conn/conn_test.go

This PR removes the usage of `github.com/tikv/pd/server/core` since we do not need it. We want to use `github.com/tikv/pd/pd-client` only in the future, so we will try to remove the usage of 
`github.com/tikv/pd/XXX` except `pd-client` in br.
- Unit test

pkg/conn/conn_test: remove github.com/tikv/pd/server/core

---

cmd/br/debug.go
pkg/mock/mockid/mockid.go

This PR uses `github.com/pingcap/br/pkg/mock/mockid` instead of `github.com/tikv/pd/pkg/mock/mockid`. We want to use `github.com/tikv/pd/pd-client` only in the future, so we will try to remove the usage of 
`github.com/tikv/pd/XXX` except `pd-client` in br.
- Unit test

cmd/br/debug.go: use br/pkg/mock/mockid instead of pd/pkg/mock/mockid

---

pkg/backup/client_test.go
tests/br_tikv_outage/run.sh

fix issue #1050 
In the case `outage-after-request`, there is a voter peer on tikv1 removed, and then a learner peer on tikv1 added.
But then quickly in the next case `outage-at-finegrained` (don't restart tikv while doing backup), tikv3 is killed.
So there is only 1 peer and 1 learner for region 257, lead to test got stuck.
It seems the case `outage-after-request` have a bad influence on the next case, so this PR try to exchange the sequence of these cases.

tests: fix br_tikv_outage learner bug

---

go.mod1
go.sum1
pkg/lightning/mydump/router.go

This PR updates tidb to the new version, and uses `github.com/pingcap/tidb/util/slice` instead of `github.com/tikv/pd/pkg/slice`. We want to use `github.com/tikv/pd/pd-client` only in the future, so we will try to remove the usage of 
`github.com/tikv/pd/XXX` except `pd-client` in br.
- Unit test

go.mod: update tidb to new version

---

compatibility/get_last_tags.sh

we found new tag like 'v5.0.2-20210628' doesn't have docker image.
change filter from 'alpha' to '-' to work around;
Tests 
- No Release note.

compatibility: filter the tags don't have corresponding docker images

---

pkg/lightning/checkpoints/checkpoints.go
pkg/lightning/common/security.go
pkg/lightning/common/security_test.go
pkg/lightning/common/util.go
pkg/lightning/config/global.go
pkg/lightning/lightning.go
pkg/lightning/mydump/loader_test.go
pkg/lightning/mydump/reader_test.go
pkg/lightning/mydump/region_test.go
pkg/lightning/restore/restore_test.go
pkg/mock/mock_cluster.go
pkg/pdutil/pd.go
pkg/restore/split_client.go
pkg/storage/compress.go
pkg/storage/compress_test.go
pkg/storage/gcs.go
pkg/storage/gcs_test.go
pkg/storage/local.go
pkg/storage/parse_test.go
pkg/storage/s3.go
pkg/storage/s3_test.go
pkg/storage/storage.go
pkg/storage/writer_test.go
pkg/trace/tracing_test.go
tests/br_key_locked/locker.go

Since we have upgraded to go 1.16 in https://github.com/pingcap/br/pull/1159, I think we can remove the [Deprecation of io/ioutil](https://golang.org/doc/go1.16#ioutil).
Remove all deprecated io/ioutil usages except `pkg/lightning/web/res_vfsdata.go`, because it was generated by vfsgen.
Tests 
- Unit test
Code changes
Side effects

*: remove deprecated io/ioutil

---

pkg/lightning/backend/local/iterator.go
pkg/lightning/backend/local/iterator_test.go

The `Seek` method of `duplicateIter` wrongly encodes the key twice, which leads to incorrect result.
Fix the bug of `Seek` and add more tests.
Tests 
- Unit test
Code changes
Side effects

lightning: fix incorrect seek of duplicate iter

---

pkg/lightning/lightning_test.go
pkg/lightning/restore/checksum_test.go
pkg/restore/batcher_test.go

Fix some test case fails when running with `--race`.
Retrieve some locks when executing some tasks, don't use sharing variables, and disabled a non trivial case (see the comment).
Tests 
- Unit test
Side effects
- `lightning_test` would be disabled when race enabled.

testing: fix some race conditions in test

---

.gitignore
pkg/lightning/restore/restore.go
pkg/lightning/restore/restore_test.go

If `Path` is empty this leads to lightning trying to open the basedir,
which then results in an error like `Error: read /home/ubuntu/csv: is a
directory` which is misleading.
Issue: https://github.com/pingcap/br/issues/1394
Tests 
- Fix the error message when trying to load CSV data in tables that don't exist.

lightning: Return error for empty path

---

pkg/summary/collector.go

fix issue: the average speed isn't accurate(https://github.com/pingcap/br/issues/1405)
change the  Calculation method for speed
Tests 
**command**
./br backup full --pd "172.16.6.117:2379" --compression-level 3 --storage "local:///home/zak/new_br"
./br restore full --pd "172.16.6.117:2379" --storage "local:///home/zak/new_br"
**log**
[2021/08/04 10:03:34.913 +08:00] [INFO] [collector.go:67] ["Full backup success summary"] [total-ranges=45] [ranges-succeed=45] [ranges-failed=0] [backup-checksum=3.515718214s] [backup-fast-checksum=7.003603ms] [backup-total-ranges=58] [backup-total-regions=77] [total-take=14.017946255s] [total-kv=15463846] [total-kv-size=1.859GB] [average-speed=132.6MB/s] ["backup data size(after compressed)"=496.8MB] …

Fix speed compute

---

pkg/restore/import.go
pkg/restore/split.go
pkg/restore/split_test.go
pkg/restore/util.go
pkg/restore/util_test.go

cherry-picking tidb#27240
=== 
Port of https://github.com/pingcap/br/pull/1377
Partially fix pingcap/br#1374
```
before：
--|-------t1 data-------|-----|---t2 data-------|
after: 
----------t1 data-------|---------t2 data-------|
Legends:
'|' the split point
'-' the key space
```
Also, `downloadSST` would find rewrite rules by **file** instead of **region start key** for now.
Tests 
The same case as pingcap/br#1374, the region count reduced about 1/2.
BR would split less regions to reduce the number of empty region after restoration.

[cherry-pick] br: less split during restoring(tidb#27240)

---

errors.toml
pkg/errors/errors.go
pkg/lightning/backend/local/local.go
pkg/lightning/backend/local/localhelper.go
pkg/lightning/backend/local/localhelper_test.go
pkg/restore/split.go
pkg/restore/util.go
pkg/restore/util_test.go

cherry-picking pingcap/tidb#27192
=== 
Currently, the implement of pd's batch scan regions can't guarantee consistency, so we add extra check for return returned region [startKey, endKey) check to ensure if there are potential range gap, the method will return an error.
Proposal: [xxx](url) 
What's Changed:
How it Works:
Tests 
Side effects
Documentation
```release-note
None
```

[cherry-pick] br: add region range check for batch scan regions(tidb#27192)

---

pkg/logutil/logging.go
pkg/restore/import.go
pkg/restore/pipeline_items.go
pkg/restore/range.go
pkg/restore/split.go
pkg/task/restore.go
pkg/utils/worker.go

cherry-picking tidb#27034
=== 
Port of https://github.com/pingcap/br/pull/1363
Before, when restoring many small tables, the batcher would probably send small batch due to the so called `AutoCommit` feature of the batcher. By this, we can make the split & scatter & restore worker more active.
But frequently send small batches isn't free. The split step is costly and I/O bounded for even small batches. For example, it costs about 3s to splitting 60 ranges, but restore those ranges typically costs only 1s. Then the restore worker get idle at most time. The restore hence has slowed down.
Instead of using a single split worker, this PR allow multi restore batches be split concurrently.
We added two **hidden** flags, `--batch-flush-interval` and `--pd-concurrency`, the former for better tuning …

[cherry-pick] restore: split & scatter regions concurrently(tidb#27034)

---

pkg/restore/db.go
tests/br_views_and_sequences/run.sh

cherry-picking pingcap/tidb#27199
=== 
Speed up create tables via omit a DDL job.
Problem Summary:
What's Changed: Remove all DDLs of rebasing autos.
How it Works: When creating table with `CreateTableWithInfo`, TiDB has rebased the auto ids via the table info:
https://github.com/pingcap/tidb/blob/a9cba7c8e8b6da512609863b56ee7265c06c50dc/ddl/ddl_api.go#L1924-L1937
It's no meaning for rebasing the auto ids again.
Tests 
```release-note
Merged the rebase auto id operation into create table.
```

[cherry-pick] skip rebase auto id(#27199)

---

pkg/backup/client.go
pkg/conn/conn.go
pkg/conn/conn_test.go
pkg/restore/client.go
pkg/restore/import.go
pkg/utils/backoff.go
pkg/utils/backoff_test.go
pkg/utils/retry.go

Cherry-pick  for pr(https://github.com/pingcap/tidb/pull/27803)  to fix issue(https://github.com/pingcap/tidb/issues/27787)
Tests 
- Unit test
```
Retry pd request and TiKV IO timeout error
```

BR: retry for PD request error and TiKV IO error (#27803)

---

pkg/lightning/backend/local/local.go

cherry-pick https://github.com/pingcap/tidb/pull/27390 to release-5.1
---
Fix the bug that lightning may stuck in merge sst files.
What's Changed:
How it Works:
Tests 
- Unit test
Side effects
Documentation
```release-note
None
```

lightning: fix infinite loop in merge ssts

---

pkg/backup/push.go
pkg/restore/import.go
pkg/utils/backoff.go
tests/br_full/run.sh

cherry-picking tidb#27423
=== 
Issue Number: close #27421 
Problem Summary:
BR used the wrapped error to get the gRPC error code, which would always returning a Unknown code.
What's Changed:
Use the unwrapped error.
How it Works:
So the code would be right.
Tests 
```release-note
Increase the robustness for restoring. 
```

[cherry-pick] restore: fix failed to retry grpc errors(tidb#27423)

---

pkg/backup/schema.go
pkg/backup/schema_test.go
pkg/lightning/mydump/region.go
pkg/lightning/mydump/region_test.go
pkg/pdutil/pd.go
pkg/storage/gcs.go
pkg/storage/gcs_test.go
pkg/storage/s3.go
pkg/storage/s3_test.go
tests/br_log_restore/run.sh
tests/br_other/run.sh
tests/lightning_duplicate_detection/run.sh
tests/lightning_error_summary/run.sh

cherry-pick pingcap/tidb#27769 and pingcap/tidb#30393 
also cherry-pick pingcap/tidb#29730 to pass integration test
also partically cherry-pick pingcap/tidb#29062 to fix some unstable integration tests
Tests 
- Unit test
Code changes
Side effects
- Fix the bug that tidb-lightning can only read at most 1000 files from gcs storage.

lightning: cherry-pick some PRs 
